In [2]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import warnings



warnings.filterwarnings('ignore')

In [67]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

train.shape, test.shape
train

,warehouse,date,orders,holiday_name,holiday,shutdown,mini_shutdown,shops_closed,winter_school_holidays,school_holidays,blackout,mov_change,frankfurt_shutdown,precipitation,snow,user_activity_1,user_activity_2,id
0,Prague_1,2020-12-05,6895.0,NaN,0,0,0,0,0,0,0,0.0,0,0.00,0.0,1722.0,32575.0,Prague_1_2020-12-05
1,Prague_1,2020-12-06,6584.0,NaN,0,0,0,0,0,0,0,0.0,0,0.00,0.0,1688.0,32507.0,Prague_1_2020-12-06
2,Prague_1,2020-12-07,7030.0,NaN,0,0,0,0,0,0,0,0.0,0,0.00,0.0,1696.0,32552.0,Prague_1_2020-12-07
3,Prague_1,2020-12-08,6550.0,NaN,0,0,0,0,0,0,0,0.0,0,0.80,0.0,1681.0,32423.0,Prague_1_2020-12-08
4,Prague_1,2020-12-09,6910.0,NaN,0,0,0,0,0,0,0,0.0,0,0.50,0.0,1704.0,32410.0,Prague_1_2020-12-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7335,Budapest_1,2024-03-10,6733.0,NaN,0,0,0,0,0,0,0,0.0,0,1.51,0.0,2983.0,27111.0,Budapest_1_2024-03-10
7336,Budapest_1,2024-03-11,6492.0,NaN,0,0,0,0,0,0,0,0.0,0,1.03,0.0,2975.0,27133.0,Budapest_1_2024-03-11
7337,Budapest_1,2024-03-12,6661.0,NaN,0,0,0,0,0,0,0,0.0,0,0.21,0.0,2974.0,27151.0,Budapest_1_2024-03-12
7338,Budapest_1,2024-03-13,6843.0,NaN,0,0,0,0,0,0,0,0.0,0,0.00,0.0,2979.0,27180.0,Budapest_1_2024-03-13
7339,Budapest_1,2024-03-14,8130.0,NaN,0,0,0,0,0,0,0,0.0,0,0.00,0.0,2953.0,27231.0,Budapest_1_2024-03-14

In [68]:
wrong_date = ['shutdown', 'mini_shutdown', 'blackout', 'frankfurt_shutdown']
print(train[['orders'] + wrong_date][(train['shutdown']==1) | (train['mini_shutdown']==1) | (train['blackout']==1) |(train['frankfurt_shutdown']==1)])

def handling_outlier(df):
    missing_features_in_test = ['user_activity_1', 'user_activity_2', 'precipitation', 'snow', 'mov_change']
    wrong_date = ['shutdown', 'mini_shutdown', 'blackout', 'frankfurt_shutdown']
    df.drop(missing_features_in_test, axis=1, errors='ignore', inplace=True)
    df['orders'] = train.apply(lambda x: x['orders'] if (x['shutdown'] + x['mini_shutdown'] + x['blackout'] + x['frankfurt_shutdown']) == 0 else np.nan, axis=1)
    df['orders'].interpolate(method='linear', axis=0, inplace=True)
    #df.drop(wrong_date, axis=1, errors='ignore', inplace=True)

handling_outlier(train)
print(train[['orders'] + wrong_date][(train['shutdown']==1) | (train['mini_shutdown']==1) | (train['blackout']==1) |(train['frankfurt_shutdown']==1)])

train.drop(wrong_date, axis=1, errors='ignore', inplace=True)

      orders  shutdown  mini_shutdown  blackout  frankfurt_shutdown
542   5832.0         0              0         1                   0
666   7003.0         0              1         0                   0
1735  5629.0         0              0         1                   0
1859  6227.0         0              1         0                   0
1908  5133.0         1              0         0                   0
2928  3675.0         0              0         1                   0
3052  4329.0         0              1         0                   0
4121  3113.0         0              0         1                   0
4245  3783.0         0              1         0                   0
5014  2058.0         0              0         1                   0
5641  1172.0         0              0         1                   0
5932  1507.0         0              0         0                   1
5933  1183.0         0              0         0                   1
6709  5116.0         0              0         1                   0
           orders  shutdown  mini_shutdown  blackout  frankfurt_shutdown
542   8899.000000         0              0         1                   0
666   8357.000000         0              1         0                   0
1735  7375.500000         0              0         1                   0
1859  6887.000000         0              1         0                   0
1908  7169.000000         1              0         0                   0
2928  5321.000000         0              0         1                   0
3052  4792.000000         0              1         0                   0
4121  5021.500000         0              0         1                   0
4245  4505.500000         0              1         0                   0
5014  2950.500000         0              0         1                   0
5641  1272.000000         0              0         1                   0
5932  1566.666667         0              0         0                   1
5933  1644.333333         0              0         0                   1
6709  5983.500000         0              0         1                   0

In [93]:
Prague_1_train = np.array(train[['orders']][(train['warehouse'] == 'Prague_1')]).reshape(1,-1)

array([[ 6895.,  6584.,  7030., ...,  9628., 10056., 11917.]])